import { test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { activeExclusionPatterns, renderExclusions } from "../dist/exclusions.js";

function policyDoc(overrides = {}) {
  return {
    version: 1,
    name: "test-policy",
    hosts: [],
    defaultAction: "allow",
    logging: "event",
    rules: [],
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Pure rendering: activeExclusionPatterns / renderExclusions, no subprocess.
// ---------------------------------------------------------------------------

test("activeExclusionPatterns: a fully-allow policy maps to zero patterns", () => {
  const patterns = activeExclusionPatterns(policyDoc());
  assert.deepEqual(patterns, []);
});

test("activeExclusionPatterns: api_key enabled pulls in secrets-shaped patterns", () => {
  const patterns = activeExclusionPatterns(policyDoc({ rules: [{ detector: "api_key", action: "warn" }] }));
  assert.ok(patterns.includes(".env"));
  assert.ok(patterns.includes("*.pem"));
  assert.ok(patterns.includes("id_rsa"));
  assert.ok(patterns.includes(".aws/**"));
  assert.ok(patterns.includes("service-account*.json"));
});

test("activeExclusionPatterns: credit_card/iban enabled pull in dump-shaped patterns, not secret ones", () => {
  const patterns = activeExclusionPatterns(
    policyDoc({ rules: [{ detector: "credit_card", action: "block" }, { detector: "iban", action: "block" }] }),
  );
  assert.ok(patterns.includes("*.sql"));
  assert.ok(patterns.includes("*.csv"));
  assert.ok(!patterns.includes(".env"), "credit_card/iban must not pull in secrets-shaped patterns");
});

test("activeExclusionPatterns: email/phone never contribute a pattern, even when blocked", () => {
  const patterns = activeExclusionPatterns(
    policyDoc({ rules: [{ detector: "email", action: "block" }, { detector: "phone", action: "block" }] }),
  );
  assert.deepEqual(patterns, [], "email/phone have no distinctive filename shape");
});

test("activeExclusionPatterns: an explicit allow overrides a strict defaultAction for that detector", () => {
  const patterns = activeExclusionPatterns(
    policyDoc({ defaultAction: "block", rules: [{ detector: "api_key", action: "allow" }] }),
  );
  // ".aws/**" is contributed only by api_key (unlike ".env", which
  // connection_string and jwt also contribute — both still active here via
  // the strict defaultAction, so ".env" alone would not isolate this case).
  assert.ok(!patterns.includes(".aws/**"), "an explicit allow rule must suppress that detector's patterns");
  // Other detectors still fall through to the strict defaultAction.
  assert.ok(patterns.includes("*.sql"));
});

test("activeExclusionPatterns: output is deduped and sorted regardless of catalog key order", () => {
  const patterns = activeExclusionPatterns(
    policyDoc({
      rules: [
        { detector: "bulk_pii", action: "block" },
        { detector: "at_svnr", action: "block" },
        { detector: "credit_card", action: "block" },
        { detector: "iban", action: "block" },
      ],
    }),
  );
  const sorted = [...patterns].sort();
  assert.deepEqual(patterns, sorted, "must already be sorted");
  assert.deepEqual(patterns, [...new Set(patterns)], "must be deduped");
});

for (const format of ["cursorignore", "copilot-yaml", "aiignore"]) {
  test(`renderExclusions(${format}): deterministic across repeated calls`, () => {
    const policy = policyDoc({ name: "det-check", rules: [{ detector: "api_key", action: "block" }] });
    const a = renderExclusions(format, policy);
    const b = renderExclusions(format, policy);
    assert.equal(a, b);
  });

  test(`renderExclusions(${format}): header names the source policy and never quotes a matched value`, () => {
    const policy = policyDoc({ name: "my-org-profile", rules: [{ detector: "api_key", action: "block" }] });
    const content = renderExclusions(format, policy);
    assert.match(content, /Generated by promptwarden emit-exclusions from policy "my-org-profile"/);
    assert.match(content, /VENDOR-SIDE AND BEST-EFFORT/);
  });

  test(`renderExclusions(${format}): empty active-pattern set still renders a well-formed file`, () => {
    const content = renderExclusions(format, policyDoc({ name: "all-allow" }));
    assert.match(content, /no active detector/);
  });
}

test("renderExclusions(cursorignore): plain gitignore-style lines, no YAML/comment framing on entries", () => {
  const content = renderExclusions("cursorignore", policyDoc({ rules: [{ detector: "api_key", action: "block" }] }));
  assert.match(content, /Cursor describes \.cursorignore as BEST-EFFORT/);
  const lines = content.split("\n");
  assert.ok(lines.includes(".env"));
  assert.ok(lines.includes("*.pem"));
  assert.ok(!lines.some((l) => l.startsWith("- ")), "cursorignore must not use YAML list syntax");
});

test("renderExclusions(copilot-yaml): YAML sequence entries, and states the Copilot CLI/agent gap", () => {
  const content = renderExclusions("copilot-yaml", policyDoc({ rules: [{ detector: "api_key", action: "block" }] }));
  assert.match(content, /NOT applied to Copilot\s*\n#\s*CLI, the Copilot coding agent, or Copilot Chat's agent mode/);
  const lines = content.split("\n");
  assert.ok(lines.includes('- ".env"'));
  assert.ok(lines.includes('- "*.pem"'));
});

test("renderExclusions(aiignore): plain lines, and states the community-convention caveat", () => {
  const content = renderExclusions("aiignore", policyDoc({ rules: [{ detector: "api_key", action: "block" }] }));
  assert.match(content, /COMMUNITY CONVENTION, comparable to \.copilotignore/);
  const lines = content.split("\n");
  assert.ok(lines.includes(".env"));
});

// ---------------------------------------------------------------------------
// CLI wiring: spawn the built bin, same black-box style as scan.test.mjs.
// ---------------------------------------------------------------------------

const cliPath = fileURLToPath(new URL("../dist/cli.js", import.meta.url));

async function tmpDir(prefix) {
  return mkdtemp(join(tmpdir(), prefix));
}

async function isolatedEnv(prefix) {
  const home = await tmpDir(`${prefix}-home-`);
  const xdgConfigHome = await tmpDir(`${prefix}-xdgcfg-`);
  const xdgStateHome = await tmpDir(`${prefix}-xdgstate-`);
  const cwd = await tmpDir(`${prefix}-cwd-`);
  return {
    cwd,
    env: {
      PATH: process.env.PATH ?? "",
      HOME: home,
      XDG_CONFIG_HOME: xdgConfigHome,
      XDG_STATE_HOME: xdgStateHome,
    },
  };
}

function runCli(args, { input, cwd, env }) {
  const result = spawnSync(process.execPath, [cliPath, ...args], {
    input: input ?? "",
    cwd,
    env,
    encoding: "utf8",
  });
  return { status: result.status, stdout: result.stdout, stderr: result.stderr };
}

test("cli: emit-exclusions with an unknown format exits 3", async () => {
  const { cwd, env } = await isolatedEnv("pw-excl-badformat");
  const { status, stderr } = runCli(["emit-exclusions", "--format", "nonsense"], { cwd, env });
  assert.equal(status, 3);
  assert.match(stderr, /unknown format "nonsense"/);
});

test("cli: emit-exclusions with no --format exits 3", async () => {
  const { cwd, env } = await isolatedEnv("pw-excl-noformat");
  const { status, stderr } = runCli(["emit-exclusions"], { cwd, env });
  assert.equal(status, 3);
  assert.match(stderr, /--format is required/);
});

test("cli: emit-exclusions --help exits 3 with usage on stderr", async () => {
  const { cwd, env } = await isolatedEnv("pw-excl-help");
  const { status, stderr } = runCli(["emit-exclusions", "--help"], { cwd, env });
  assert.equal(status, 3);
  assert.match(stderr, /Usage: promptwarden emit-exclusions/);
});

test("cli: emit-exclusions an unknown flag exits 3", async () => {
  const { cwd, env } = await isolatedEnv("pw-excl-unknownflag");
  const { status, stderr } = runCli(["emit-exclusions", "--format", "cursorignore", "--nope"], { cwd, env });
  assert.equal(status, 3);
  assert.match(stderr, /unknown argument/i);
});

test("cli: emit-exclusions with no --out prints the rendered file to stdout and exits 0", async () => {
  const { cwd, env } = await isolatedEnv("pw-excl-stdout");
  const { status, stdout } = runCli(["emit-exclusions", "--format", "cursorignore"], { cwd, env });
  assert.equal(status, 0);
  assert.match(stdout, /Generated by promptwarden emit-exclusions/);
});

test("cli: --out writes the rendered file to disk and exits 0", async () => {
  const { cwd, env } = await isolatedEnv("pw-excl-out");
  const policyPath = join(cwd, "policy.json");
  await writeFile(
    policyPath,
    JSON.stringify({
      version: 1,
      name: "writes-to-disk",
      hosts: [],
      defaultAction: "allow",
      logging: "off",
      rules: [{ detector: "api_key", action: "block" }],
    }),
  );
  const outPath = join(cwd, "out", ".cursorignore");
  const { status, stdout } = runCli(
    ["emit-exclusions", "--format", "cursorignore", "--out", outPath],
    { cwd, env: { ...env, PROMPTWARDEN_POLICY: policyPath } },
  );
  assert.equal(status, 0);
  assert.equal(stdout, "", "with --out, nothing should be printed to stdout");

  const written = await readFile(outPath, "utf8");
  assert.match(written, /Generated by promptwarden emit-exclusions from policy "writes-to-disk"/);
  assert.ok(written.includes(".env"));
});

test("cli: emit-exclusions --format copilot-yaml renders a YAML list end to end", async () => {
  const { cwd, env } = await isolatedEnv("pw-excl-copilotyaml");
  const policyPath = join(cwd, "policy.json");
  await writeFile(
    policyPath,
    JSON.stringify({
      version: 1,
      name: "copilot-check",
      hosts: [],
      defaultAction: "allow",
      logging: "off",
      rules: [{ detector: "credit_card", action: "block" }],
    }),
  );
  const { status, stdout } = runCli(["emit-exclusions", "--format", "copilot-yaml"], {
    cwd,
    env: { ...env, PROMPTWARDEN_POLICY: policyPath },
  });
  assert.equal(status, 0);
  assert.match(stdout, /- "\*\.sql"/);
});
